
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYUhFOGtheU94Mjh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBMU1qRXhNelExTWpoYUZ3MHpOakExTVRneE16VXdNamhhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURncTBjd0VNRmYvd1dDcUVtKzlSS215SnF2QTdESVI3S1RqYkV6VG5RU0RRMFNNT3hCUGo2aW5zVkIKWEFlUXJBSm42ZlFtRFVpSGZWSG5IUFJxMm5OOVlOZWp4Skt3cUdOc0xzZnVzbHdHUDZUV3RpQlUyTUo1V285VwpnSFdkb2VsSmR0dEpUdGVtNHNjVE5YLzFlUmZPVUdCU0JtTEh5cWZYbG53cDZFVElJSDA5WlVIMTRnOHhpRlpKCk1zTHpFemNudnJ3dzVMUk1aTCtad29QUytvZHQ3RmpQZGIzT1BLNFgwS0o2cUdHbThBd0JORitHWlBQM0N6Q3AKRTVQQjJscWovbkhOSE50MWRFN1Z5bDdoR0trMTZEUnMxUlRyUmpWL1B1RTBJWkdRVGlXYVRUQnRjZUQ4dElqTgpDbEF5ZXRJY2hadkhFc21qbWJ3WHNwRWFMQUhWQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUWVcybGpIc2xsaThGWS9GOWREeHVMWktGdUxqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRREN2VWFYZ2V4egp4b1ZLSm8zVDVhenJrWDdTUC92cmVQN0xEbHdOSVp5RmRqZFJ6WTR3cW90R2VMbWZmbWd4ZUtMSUg4enFXQjg4CkdOUm56bWhJWGJ5L2h2WWQ4Q2lONGpCbnMzd2pLU3o2dGhvb29ldmlzNVZLdnpZdTBhSUthcU5YWUpPZ1hLQS8KZlZpbEdNZ3NRRUlHWkt2WDlPbEZrcUdpOHdPVEJWd0VsaVhMbEdEMGpWSUJtTmdvSTZ4cy9md3NCTU9TSXM1agp3cnl2ZU12WmxMdmM2azRmaDF0Ymp5RjIwRGtxODBUR05QWUE4bXR5a0ZjSStVbmRMUXJLa3NZbEZCSG1yS0lFCmtvVmVUWG1EMmFrb0NUSmlVdFN2eXVXWC9CRGdIMjRkMHNMR0IyYzFlMS8zR0V6WTIvTTRDRDU2UDZ1dFdkei8KM2NzQTY4V25xN1UrCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://4dc20715-cbf3-4c86-8879-829456d312a7.uk-lon-2-gw.linodelke.net:443
  name: lke606465

users:
- name: lke606465-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InF2X3JyMFEyVDdMTjh5QWhJbEo3dHNnZXdIM0xuWjE0MENVcU00NmFmMWcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tenZtNnEiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZmMxMzJiMjUtNzAzNC00NTI5LTk4ZGUtZjUzYjI0ODNhN2YwIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.Vo2vQhBFjkSkSNjZmPnDNxyTkGLiS6dNSy0XYnoHP_-_l1rs-qsIkXsKwkSPmedXJgz45xXR38u0hk_mOaBJKXeiePEqGl1A-Y1WEEktv7otyQLL8gb4R9MXw1Qvf3fVunPEFTz9ndiywWr-da7EMy2goraviSAxLihgMzO797ozd3pRCe4o5pN5loxCZoDlIukz7wnqlq7aCqk6ucTlZQxQx81xDv3nKXwn9miAzmIiY8OPxcywS5X7tmTXrMPPBhAVKeIHWn0ozt0p7l5o2HlB4dvjTkXSl2zw70TjqS5KbRTuNB6xZ5ZMP1scZGRlLL01BEG3qGUStNcn5-3_aw

contexts:
- context:
    cluster: lke606465
    namespace: default
    user: lke606465-admin
  name: lke606465-ctx

current-context: lke606465-ctx
