
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTnhwbStEZlJPV0l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBMU1qSXdPRFExTkROYUZ3MHpOakExTVRrd09EVXdORE5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN5RHd3ZzRwRmZtS2xtakpXZmhOZlNieHdiZEVMUHlrUzZycVhVTWVzVVJ1aVNIWnVqSUo3NDk3NHIKSlZIelkwNmVSUmpac2tiUGpnR0JLUUtDZHowU2dPRmhYWGhhbExJQ1ZXQm1iSVZVYmk4bUxyQW5oZGRrM1RrUgo3RGZqZWdMeDBEdit6VWtSbWdGSVlSUVl1QXpxcHBrV3pNZVRmT0JCa2JtcUVveFZ3b1V1emxvU1FsOG9kcW5yCkRCNkhhM3VEZld3MktNUlMzMEF6UmJoMGNNWXZNemxIbXg4Z2hwbVUwWkptNWw0ZzFuRHd2QlV5QWFmUVdFeXgKdjNUUGhQYjlKWDZLaFdUSlJCTzByVGJpR000VXp3NmMydkNhN1o3cGdSakMvaWl5L2JBTk9yMkgwZzZpYzFSNwpxNUNnSW5EM2hUbTFkYmNHM2xTOWo3dmRqanZIQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSZldoUUkzSkxEUDhzNVMwaTJreDMzVGErd0hqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnpNb2VhUXQ4ZwoxaURsZFdTYk5wU1RjOUtlL0lpOXlTdm5HdklQRU04TktUaFYzUUp5S1FJQTNEdG83dEtkdlk1RS81S3NxZldICmRkL2ZJdVJ3ZHowZlNhUmpKY3ByTFIrS1RxOWJxRVYxbWIxeE12VStlejYvcXZZbnRMUlZOTTVMMFg4NHl1RkkKWGc5MnY5eS9nU1hrZ0J1Z2dsVzg1WitoU053NGxFNFJEbHcvaDVJTkVlUDNXbUMyOVFCSHJhVCtvbXpLM1I1ZgpGYlN1dEdHbWcxb0ZvSlU1WWRlU0FzV2orVyttczUrYjlxeUlFSFBVbHl2MDFIZkJJYlFUNVpMMzFZUVdpeGJhCnUwUHJRQ3NZQy8zQlh6TGtlVXVuOG8veis1R1A0UkFBSWZxQ2ZCQXVab2RTSHVod0RvVkJkY1FNTmVaY2hqTVAKbE9WQXNBS1J0TjAxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://2f650801-0c08-475b-a71d-b021f5a815e6.uk-lon-2-gw.linodelke.net:443
  name: lke606732

users:
- name: lke606732-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Im1xZEk3TjJoYVNqQVBrbW5FWjU4cXV4SENGSXZLZ3V1ajF6Wk9acjUxaEkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tZjc2OWgiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZGZjNDdmMjUtZTk2ZC00MzU0LWFjODEtMmVhNzA5ZjExOWEzIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.jFbmcfORgT7q2v_JKOyOyZJsX8eBgw7i3e7NBuQvDrfFovPLT2RsxDdBftNOUzbkxnW-VI-ol98lAA3WL-_ki7szU74qHzA2RUglDyrtP3Za6klSQRH4UAbW1W2rw_cL4g0YBrvJnvPtGdzbN4H5WC2Z7tOglqoe1X6oeq8T6sD6i997BVF48l1-SQ28J8UyXW115CwbXGrDyWqIIsu61K5xu_z-hha8_uVKWRy_LrYvF99XAvvYgLrEh4sDssaGueUbGJo8QrQuayURqQosKczApT-ODv_k9H7PYZzsPh2FmR-khqiQYvZFvZHwoC06CgM9wkJRCpg2SD31duK9WQ

contexts:
- context:
    cluster: lke606732
    namespace: default
    user: lke606732-admin
  name: lke606732-ctx

current-context: lke606732-ctx
